version: "3"
services:
  app:
    image: perceiver_io_recommender
    container_name: perceiver_io_recommender
    tty: true
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: ${BUILD_TARGET:-non-root}
      args:
        UID: ${UID}
    volumes: 
      - ../:/root/perceiver_io_recommender/
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
      - ${DATASET_PATH}:/root/perceiver_io_recommender/dataset
      - ${LOG_PATH}:/root/perceiver_io_recommender/logs
      - ${MODEL_PATH}:/root/perceiver_io_recommender/models
      - ${VENV_PATH}:/root/perceiver_io_recommender/.venv
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT}
      - ${TENSORBOARD_PORT}:${TENSORBOARD_PORT}
    ipc: host  # share shm with host
