_target_: mind_recommenders_pytorch.train.models.news_recommendation_model.NewsRecommendationModel
news_encoder:
  _target_: mind_recommenders_pytorch.train.models.perceiver_io.perceiver_io_news_encoder.PerceiverIONewsEncoder
  token_embedding_layer: ${embedding_layer}
  article_attributes: ${hparams.article_attributes}

  num_heads: ${hparams.num_heads}
  num_latents: ${hparams.num_latents}
  latent_dim: ${hparams.latent_dim}
  num_self_attn_per_block: ${hparams.num_self_attn_per_block}
  num_blocks: ${hparams.num_blocks}
  decoder_query_dim: ${hparams.decoder_query_dim}

  word_pos_emb: ${hparams.word_pos_emb}
  seq_pos_emb: ${hparams.seq_pos_emb}
  feat_type_emb: ${hparams.feat_type_emb}

  max_history_length: ${hparams.max_history_length}
  max_title_length: ${hparams.max_title_length}
  max_body_length: ${hparams.max_body_length}

  n_categories: ${hparams.n_categories}
  n_subcategories: ${hparams.n_subcategories}

user_encoder:
  _target_:  mind_recommenders_pytorch.train.models.perceiver_io.perceiver_io_user_encoder.PerceiverIOUserEncoder

